apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #  - namespace/
  #- secrets/sealed-django-secret.yaml
  #- secrets/sealed-db-secret.yaml
  - volume/postgres-pv.yaml
  - volume/postgres-pvc.yaml
  - deployment/django-deployment.yaml
  - deployment/postgres-deployment.yaml
  - service/django-service.yaml
  - service/postgres-service.yaml
  
