apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-secret-sync
  namespace: todo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: django-secret  # Changed to match deployment (no 's')
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: django-secret
